---
stages:
- name: Deploy
  inputs:
  - service: ${REPO}
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  properties:
  - name: CLOUD_FUNCTIONS_API_ENDPOINT
    value: ${CLOUD_FUNCTIONS_API_ENDPOINT}
    type: text
  - name: CLOUD_FUNCTIONS_API_KEY
    value: ${CLOUD_FUNCTIONS_API_KEY}
    type: secure
  - name: MESSAGE_HUB_API_KEY
    value: ${MESSAGE_HUB_API_KEY}
    type: secure
  - name: MESSAGE_HUB_USER
    value: ${MESSAGE_HUB_USER}
    type: secure
  - name: MESSAGE_HUB_PASSWORD
    value: ${MESSAGE_HUB_PASSWORD}
    type: secure
  - name: MESSAGE_HUB_KAFKA_REST_URL
    value: ${MESSAGE_HUB_KAFKA_REST_URL}
    type: secure
  - name: MESSAGE_HUB_KAFKA_ADMIN_URL
    value: ${MESSAGE_HUB_KAFKA_ADMIN_URL}
    type: text
  - name: MESSAGE_HUB_KAFKA_INSTANCE
    value: ${MESSAGE_HUB_KAFKA_INSTANCE}
    type: text
  - name: MESSAGE_HUB_SRC_TOPIC
    value: ${MESSAGE_HUB_SRC_TOPIC}
    type: text
  - name: MESSAGE_HUB_DEST_TOPIC
    value: ${MESSAGE_HUB_DEST_TOPIC}
    type: secure
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
      application: messagehubdataprocessing
    script: |+
      #!/bin/bash

      set -x
      set +e

      # Download IBM Cloud CLI and Cloud Functions plugin 
      # curl -fsSL https://clis.ng.bluemix.net/install/linux | sh
      # bx plugin install Cloud-Functions -r Bluemix

      # Download the wskdeploy CLI
      curl -OL https://github.com/apache/incubator-openwhisk-wskdeploy/releases/download/latest/wskdeploy-latest-linux-amd64.tgz
      tar xf wskdeploy-latest-linux-amd64.tgz
      chmod 755 wskdeploy

      # Make service credentials available to your environment
      # source local.env

      # Expects these environment variables
      export APIHOST=openwhisk.ng.bluemix.net
      export NAMESPACE=_
      export APIVERSION=v1
      export AUTH=$CLOUD_FUNCTIONS_API_KEY
      export APIGW_ACCESS_TOKEN=

      # bx wsk package refresh

      # Deploy the packages, actions, triggers, and rules using your preferred language
      cd runtimes/nodejs # Or runtimes/[php|python|swift]
      ./wskdeploy

hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
