---
stages:
- name: DEPLOY
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  properties:
  - name: LOAD_ENV_FILE
    value: 'false'
    type: text
  - name: IBM_CLOUD_LOGIN
    value: 'true'
    type: text
  jobs:
  - name: Deploy
    type: deployer
    deploy_type: customimage
    script: |-
      #!/bin/bash

      cd ibmcloud-wsk
      ./deploy.sh --install
    docker_image: jamesthomas/cloud-functions-tools
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish
properties:
- name: KAFKA_INSTANCE
  value: ${KAFKA_INSTANCE}
  type: text
- name: KAFKA_CREDS
  value: ${KAFKA_CREDS}
  type: text
- name: SRC_TOPIC
  value: ${SRC_TOPIC}
  type: text
- name: DEST_TOPIC
  value: ${DEST_TOPIC}
  type: text
- name: IBMCLOUD_API_KEY
  value: ${IBMCLOUD_API_KEY}
  type: text
- name: IBMCLOUD_SPACE
  value: ${IBMCLOUD_SPACE}
  type: text
- name: IBMCLOUD_ORG
  value: ${IBMCLOUD_ORG}
  type: text
- name: IBMCLOUD_REGION
  value: ${IBMCLOUD_REGION}
  type: text
